dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION="4.2" GUZZLE_VERSION="3.*"
  - SYMFONY_VERSION="4.3" GUZZLE_VERSION="3.*"
  - SYMFONY_VERSION="4.4" GUZZLE_VERSION="3.*"
  - SYMFONY_VERSION="4.*" GUZZLE_VERSION="3.*"
  - SYMFONY_VERSION="5.*" GUZZLE_VERSION="3.*"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update
  - composer require guzzle/http:${GUZZLE_VERSION} --no-update
  - composer install -n --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
